"""Project path resolution.

Every module that needs a directory asks this module for it. Nothing anywhere
else in the codebase constructs a path relative to ``__file__``, and nothing
uses a relative path that depends on the current working directory --- that is
how a notebook silently writes its output somewhere a script cannot find it.

Resolution order for the project root:

1. ``DSA_PROJECT_ROOT`` environment variable, if set.
2. The nearest ancestor of this file containing ``pyproject.toml``.

Directories are created on demand rather than at import time, so importing
``dsa`` never has a filesystem side effect.
"""

from __future__ import annotations

import os
from pathlib import Path

__all__ = [
    "project_root",
    "config_dir",
    "data_raw",
    "data_interim",
    "data_clean",
    "models_dir",
    "figures_dir",
    "reports_dir",
    "logs_dir",
    "ensure_dir",
    "project_dirs",
]

_ROOT_MARKER = "pyproject.toml"


def _find_root_from_file() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / _ROOT_MARKER).is_file():
            return parent
    # Fall back to the package's grandparent (src/dsa -> src -> root). This
    # keeps things working from a zip/egg install where pyproject is absent.
    return here.parents[2]


def project_root() -> Path:
    """Absolute path to the repository root."""
    env = os.environ.get("DSA_PROJECT_ROOT")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.is_dir():
            raise FileNotFoundError(f"DSA_PROJECT_ROOT points at a missing directory: {p}")
        return p
    return _find_root_from_file()


def config_dir() -> Path:
    """Directory holding the YAML configuration files."""
    env = os.environ.get("DSA_CONFIG_DIR")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.is_dir():
            raise FileNotFoundError(f"DSA_CONFIG_DIR points at a missing directory: {p}")
        return p
    return project_root() / "config"


def ensure_dir(path: Path) -> Path:
    """Create ``path`` (and parents) if needed and return it."""
    path.mkdir(parents=True, exist_ok=True)
    return path


def data_raw() -> Path:
    """Downloaded data exactly as received. NEVER edited in place."""
    return ensure_dir(project_root() / "data" / "raw")


def data_interim() -> Path:
    """Intermediate artefacts of the cleaning pipeline."""
    return ensure_dir(project_root() / "data" / "interim")


def data_clean() -> Path:
    """Adjusted, gap-checked, analysis-ready parquet."""
    return ensure_dir(project_root() / "data" / "clean")


def models_dir() -> Path:
    """Serialised model artefacts (XGBoost boosters, LSTM state dicts)."""
    return ensure_dir(project_root() / "models")


def figures_dir() -> Path:
    """Generated figures. Regenerated by `make`, never edited by hand."""
    return ensure_dir(project_root() / "figures")


def reports_dir() -> Path:
    """Generated tables, run logs and the final writeup."""
    return ensure_dir(project_root() / "reports")


def logs_dir() -> Path:
    """Rotating run logs."""
    return ensure_dir(project_root() / "logs")


def project_dirs() -> dict[str, Path]:
    """Every managed directory, for health checks and diagnostics."""
    root = project_root()
    return {
        "root": root,
        "config": config_dir(),
        "data/raw": root / "data" / "raw",
        "data/interim": root / "data" / "interim",
        "data/clean": root / "data" / "clean",
        "src": root / "src",
        "tests": root / "tests",
        "notebooks": root / "notebooks",
        "models": root / "models",
        "reports": root / "reports",
        "figures": root / "figures",
        "logs": root / "logs",
        "app": root / "app",
        "scripts": root / "scripts",
    }
