# ---------------------------------------------------------------------------
# DeepStatArb
# Spec Sec 12: figures are regenerated by make, never by hand.
#
# WINDOWS USERS: GNU make is usually absent. Every target below is a one-line
# command you can paste directly, or use the python equivalents in scripts/.
# ---------------------------------------------------------------------------
PY ?= python

.PHONY: help setup test test-fast test-network test-leakage lint fmt check clean \n        check-data data universe quality screen backtest study all

help:
	@echo "setup      install the package and dev dependencies (editable)"
	@echo "check      environment / dependency health check"
	@echo "test       run the full test suite"
	@echo "test-fast  run tests, skipping slow and network-bound ones"
	@echo "lint       ruff check"
	@echo "fmt        ruff format"
	@echo "clean      remove caches and build artefacts"
	@echo ""
	@echo "-- pipeline --"
	@echo "check-data build the NSE price panel (resumable; ~2 min of downloads)"
	@echo "data       build the NSE price panel (resumable; ~2 min of downloads)"
	@echo "universe   re-filter and re-freeze config/universe.yaml"
	@echo "quality    data-quality report over the frozen universe"
	@echo ""
	@echo "-- not built yet --"
	@echo "screen     [Day 4-6]   cointegration screen + BH FDR funnel"
	@echo "backtest   [Day 10-12] walk-forward backtest with Indian costs"
	@echo "study      [Day 16-18] Kaplan-Meier shelf-life analysis"

setup:
	$(PY) -m pip install -e ".[dev]"

check:
	$(PY) scripts/check_env.py

test:
	$(PY) -m pytest

test-fast:
	$(PY) -m pytest -m "not slow and not network"

test-network:
	$(PY) -m pytest -m network

test-leakage:
	$(PY) -m pytest -m leakage

lint:
	$(PY) -m ruff check src tests scripts

fmt:
	$(PY) -m ruff format src tests scripts

clean:
	$(PY) -c "import shutil,pathlib; [shutil.rmtree(p,ignore_errors=True) for p in pathlib.Path('.').rglob('__pycache__')]"
	$(PY) -c "import shutil; [shutil.rmtree(d,ignore_errors=True) for d in ['.pytest_cache','.ruff_cache','build','dist']]"

# --- Data layer (Day 2) -----------------------------------------------------
check-data:
	$(PY) scripts/check_data_connection.py

data:
	$(PY) scripts/build_dataset.py --stage all

universe:
	$(PY) scripts/build_universe.py

quality:
	$(PY) scripts/run_quality_report.py --universe-only

# --- Not yet implemented. These fail loudly rather than silently no-op, so a
# --- reviewer can never mistake an unbuilt stage for a passing one.
screen backtest study all:
	@echo "TARGET '$@' IS NOT IMPLEMENTED YET (see Makefile help for the day it lands)." && exit 1
